[project]
name = "nonebot-plugin-learning-chat"
version = "0.4.1"
description = "Nonebot2 plugin to learn what your group members say."
authors = [
    { name = "MerCuJerry", email = "mercujerry@gmail.com" },
    { name = "CMHopeSunshine", email = "277073121@qq.com" }
]
requires-python = ">=3.10,<4"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["nonebot2"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "nonebot2>=2.5.0,<3",
    "nonebot-adapter-milky>=1.2.0,<2",
    "nonebot-plugin-apscheduler>=0.5.0,<0.6",
    "nonebot-plugin-localstore>=0.7.4",
    "nonebot-plugin-orm[sqlite]>=0.8.3,<0.9",
    "jieba>=0.42.1,<0.43",
    "nicegui>=3.16.0,<4",
    "pydantic>=2.0.0,<3",
    "fastapi>=0.141.0"
]

[project.urls]
Homepage = "https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat"

[project.optional-dependencies]
fast = [
    "jieba-fast>=0.53"
]
dev = [
    "nb-cli>=1.0.0",
    "nonebot2[fastapi,httpx,websockets]>=2.5.0"
]

[tool.uv]

[tool.uv.build-backend]
module-root = ""
source-include = ["nonebot_plugin_learning_chat"]

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.nonebot]
plugin_dirs = []
builtin_plugins = []

[tool.nonebot.plugins]
"@local" = []
nonebot-plugin-learning-chat = ["nonebot_plugin_learning_chat"]

[tool.nonebot.adapters]
nonebot-adapter-milky = [
    { name = "nonebot-adapter-milky", module_name = "nonebot.adapters.milky" }
]
"@local" = []
