[project]
name = "nonebot-plugin-learning-chat"
version = "0.4.1"
description = "Nonebot2 plugin to learn what your group members say."
authors = [
    { name = "MerCuJerry", email = "mercujerry@gmail.com" },
    { name = "CMHopeSunshine", email = "277073121@qq.com" }
]
requires-python = ">=3.10,<4"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["nonebot2"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "nonebot2>=2.5.0,<3",
    "nonebot-adapter-milky>=1.2.0,<2",
    "nonebot-plugin-apscheduler>=0.5.0,<0.6",
    "nonebot-plugin-localstore>=0.7.4",
    "nonebot-plugin-orm[sqlite]>=0.8.3,<0.9",
    "jieba>=0.42.1,<0.43",
    "nicegui>=3.16.0,<4",
    "pydantic>=2.0.0,<3",
    "fastapi>=0.141.0"
]

[project.urls]
Homepage = "https://github.com/CMHopeSunshine/nonebot-plugin-learning-chat"

[project.optional-dependencies]
fast = [
    "jieba-fast>=0.53"
]
dev = [
    "nb-cli>=1.0.0",
    "nonebot2[fastapi,httpx,websockets]>=2.5.0"
]

[tool.uv]

[tool.uv.build-backend]
module-root = ""
source-include = ["nonebot_plugin_learning_chat"]

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.lint]
select = [
    "F",     # pyflakes
    "E",     # pycodestyle errors
    "W",     # pycodestyle warnings
    "I",     # isort
    "N",     # PEP8-naming
    "UP",    # pyupgrade
    "YTT",   # flake8-2020
    "ASYNC", # flake8-async
    "S",     # flake8-bandit
    "BLE",   # flake8-blind-except
    "FBT",   # flake8-boolean-trap
    "B",     # flake8-bugbear
    "A",     # flake8-builtins
    "COM",   # flake8-commas
    "C4",    # flake8-comprehensions
    "DTZ",   # flake8-datetimez
    "T10",   # flake8-debugger
    "FA",    # flake8-future-annotations
    "ISC",   # flake8-implicit-str-concat
    "ICN",   # flake8-import-conventions
    "PIE",   # flake8-pie
    "T20",   # flake8-print
    "PYI",   # flake8-pyi
    "Q",     # flake8-quotes
    "RSE",   # flake8-raise
    "RET",   # flake8-return
    "SLOT",  # flake8-slots
    "SIM",   # flake8-simplify
    "TID",   # flake8-tidy-imports
    "TC",    # flake8-type-checking
    "ARG",   # flake8-unused-arguments
    "PTH",   # flake8-use-pathlib
    # "ERA",   # eradicate
    "PD",   # pandas-vet
    "PGH",  # pygrep-hooks
    "PL",   # pylint
    "TRY",  # tryceratops
    "FLY",  # flynt
    "FAST", # FastAPI
    "PERF", # Perflint
    "FURB", # refurb
    "RUF",  # Ruff-specific rules
]
ignore = [
    "E501",
    "BLE001",
    "E402",
    "PGH003",
    "RUF003",
    "RUF001",
    "PLR0911",
    "PLR0912",
    "PLR0915",
    "S101",
    "RET505",
    "S311", # 不是这也不是安全目的啊
    "PLR2004",
    "PLR0913",
    "PERF203",
]

[tool.nonebot]
plugin_dirs = []
builtin_plugins = []

[tool.nonebot.plugins]
"@local" = []
nonebot-plugin-learning-chat = ["nonebot_plugin_learning_chat"]

[tool.nonebot.adapters]
nonebot-adapter-milky = [
    { name = "nonebot-adapter-milky", module_name = "nonebot.adapters.milky" }
]
"@local" = []
